src/onlineschool/courses/urls.py
from courses import views
from django.contrib import admin
from django.urls import path
from django.urls import include, path


app_name='courses'


urlpatterns=[
path('watch/',views.watch,name='watch'),
path('allcourses/',views.allcourses,name='allcourses'),
path('course<int:course_pk>/',views.watchcourse,name='course'),
path('course<int:course_pk>/modules/module<int:module_pk>',views.watchlesson,name='watchlesson')

]
# будет watch/id видео 
# modules/ id курса
# будет 

src/onlineschool/onlineschool/urls.py
from django.contrib import admin
from django.urls import path
from users import views 
from main import views 
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/',include('users.urls')),
    # path('signup/',views.signup,name='signup'),
    # path('signin/',views.signin,name='signin'),
    path("", views.home,name='home'),
    path('courses/',include('courses.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/onlineschool/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views 
from django.urls import include, path


app_name='users'


urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('signin/',views.signin,name='signin'),
    path('signout/',views.signout,name='signout'),
]

src/onlineschool/courses/models.py
from django.db import models
class Course(models.Model):
    title=models.CharField(max_length=100,blank=True)
    memo=models.TextField(blank=True)
    hours=models.IntegerField(blank=True)
    price=models.IntegerField()
    def __str__(self):
        return str(self.title) + str(self.id)
    

class Module(models.Model):
    title=models.CharField(max_length=100,blank=True)
    memo=models.TextField(blank=True)
    course_id=models.ForeignKey(Course,on_delete=models.CASCADE)
    number=models.IntegerField(blank=True)
    def __str__(self):
        return str(self.title) + str(self.id)
    

class Lesson(models.Model):
    title=models.CharField(max_length=100,blank=True)
    memo=models.TextField(blank=True)
    video=models.FileField(upload_to='courses/videos/')
    module=models.ForeignKey(Module,on_delete=models.CASCADE)
    number=models.IntegerField(blank=True)
    def __str__(self):
        return str(self.title) + str(self.id)
    

# class DownModule(models.Model):
#     title=models.CharField(max_length=100,blank=True)
#     memo=models.TextField(blank=True)
#     module_id=models.ForeignKey(Module,on_delete=models.CASCADE)
#     number=models.IntegerField(blank=True)

# class Videos(models.Model):
#     title=models.CharField(max_length=100,blank=True)
#     video=models.FileField(upload_to='courses/videos/')
# Create your models here.

src/onlineschool/courses/views.py
from django.shortcuts import render,get_object_or_404
from .models import * 


def allcourses(request):
    courses=Course.objects.all()
    return render(request,'courses/allcourses.html',{'courses':courses})


def watchcourse(request,course_pk):
    course=get_object_or_404(Course,pk=course_pk)
    modules=Module.objects.filter(course_id=course_pk)
    return render(request,'courses/course.html',{'course':course,'modules':modules})


def watchlesson(request,course_pk,module_pk):
    lessons=Lesson.objects.filter(module_id=module_pk)
    return render(request,'courses/lesson.html',{'lessons':lessons})

def watch(request):
    return render(request,'courses/watch.html')
# Create your views here.

src/onlineschool/main/views.py
from django.shortcuts import render
def home(request):
    return render(request,'main/home.html')
# Create your views here.

src/onlineschool/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method=='GET':
        return render(request,'users/signup.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1']==request.POST['password2']:
            try: 
                user=User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                user.save()
                return redirect('home')
            except IntegrityError: 
                return render(request, 'users/signup.html', {'form':UserCreationForm(), 'error':'That username has already been taken. Please choose a new username'})
        else: 
            return render(request, 'users/signup.html', {'form':UserCreationForm(), 'error':'Passwords did not match'})
 

def signin(request):
    if request.method=='GET':
        return render(request,'users/signin.html',{'form':AuthenticationForm()})
    else: 
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'users/signin.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('home')
        
        
@login_required
def signout(request):
    if request.method=='POST':
        logout(request)
        return redirect('home')
    
# Create your views here.

src/onlineschool/courses/templates/courses/allcourses.html
{% extends "main/base.html" %}
{% block content %}
<h2>allcourses</h2>
{% for course in courses %}
<a href="{% url 'courses:course' course.id %}">{{ course }}</a>

<br>
{% endfor %}
{% endblock %}

src/onlineschool/courses/templates/courses/course.html
{{ course.title }}
<br>
{{ course.memo }}
<br>
{% for module in modules %}
<a href="{% url 'courses:watchlesson' course.id module.id %}"> ссылка </a>

<br>
{{ module.memo }}
<br>
{% endfor %}

src/onlineschool/courses/templates/courses/lesson.html
{% for lesson in lessons %}
<h2>
    {{ lesson.title }}
</h2>
<h3>
    {{lesson.memo}}
</h3>
<video height="300" width="300">
    <source src="{{ lesson.video.url }}">
</video>
<br>
{% endfor %}

src/onlineschool/courses/templates/courses/modules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

src/onlineschool/courses/templates/courses/watch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    watch
</body>
</html>

src/onlineschool/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<header>
    {% if user.is_authenticated  %}
    <a href="{% url 'home' %}"> домой </a>
    <form method="POST" action="{% url 'users:signout' %}">
        {% csrf_token %}
        <button  type="submit" >Выйти</button>
    </form>
    вы зарегестрированы как {{ user.username }}
    {% else %}
    <a  href="{% url 'users:signup' %}"> зарегестрироваться </a>
    <a  href="{% url 'users:signin' %}"> войти </a>
    {% endif %}
</header>
<br>
<br>
<br>
{% block content %}{% endblock %}
</body>
</html>

src/onlineschool/main/templates/main/home.html
{% extends "main/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    home
</body>
{% endblock %}
</html>

src/onlineschool/users/templates/users/signin.html
{% extends "main/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
<button type="submit">
    Войти
</button>
    </form>
    {{ error }}
    {% endblock %}

</body>
</html>